# 피마인디언 당뇨병 사례

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 2021
np.random.seed(seed)
tf.random.set_seed(seed)

## 데이터 전처리

In [ ]:
# 파일 업로드
from google.colab import files
uploaded = files.upload()
uploaded

Saving pima-indians-diabetes.csv to pima-indians-diabetes.csv


{'pima-indians-diabetes.csv': b'6,148,72,35,0,33.6,0.627,50,1\n1,85,66,29,0,26.6,0.351,31,0\n8,183,64,0,0,23.3,0.672,32,1\n1,89,66,23,94,28.1,0.167,21,0\n0,137,40,35,168,43.1,2.288,33,1\n5,116,74,0,0,25.6,0.201,30,0\n3,78,50,32,88,31.0,0.248,26,1\n10,115,0,0,0,35.3,0.134,29,0\n2,197,70,45,543,30.5,0.158,53,1\n8,125,96,0,0,0.0,0.232,54,1\n4,110,92,0,0,37.6,0.191,30,0\n10,168,74,0,0,38.0,0.537,34,1\n10,139,80,0,0,27.1,1.441,57,0\n1,189,60,23,846,30.1,0.398,59,1\n5,166,72,19,175,25.8,0.587,51,1\n7,100,0,0,0,30.0,0.484,32,1\n0,118,84,47,230,45.8,0.551,31,1\n7,107,74,0,0,29.6,0.254,31,1\n1,103,30,38,83,43.3,0.183,33,0\n1,115,70,30,96,34.6,0.529,32,1\n3,126,88,41,235,39.3,0.704,27,0\n8,99,84,0,0,35.4,0.388,50,0\n7,196,90,0,0,39.8,0.451,41,1\n9,119,80,35,0,29.0,0.263,29,1\n11,143,94,33,146,36.6,0.254,51,1\n10,125,70,26,115,31.1,0.205,41,1\n7,147,76,0,0,39.4,0.257,43,1\n1,97,66,15,140,23.2,0.487,22,0\n13,145,82,19,110,22.2,0.245,57,0\n5,117,92,0,0,34.1,0.337,38,0\n5,109,75,26,0,36.0,0.546,60,0

In [ ]:
# 파일 불러오기
filename = list(uploaded.keys())[0]
Data_set = np.loadtxt(filename, delimiter=',')
Data_set[:3, :]

array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   ,  29.   ,   0.   ,  26.6  ,   0.351,
         31.   ,   0.   ],
       [  8.   , 183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672,
         32.   ,   1.   ]])

In [ ]:
# 데이터 정규화
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_norm = scaler.fit_transform(Data_set[:, :-1])

In [ ]:
# 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_norm, Data_set[:, -1], 
    stratify=Data_set[:, -1],
    random_state=seed
)
X_train.shape, X_test.shape

((576, 8), (192, 8))

## 모델 정의/설정/학습/평가

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# 모델 정의
model = Sequential()
model.add(Dense(12, input_shape=(8,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                108       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 모델 설정
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [ ]:
# 모델 실행
history = model.fit(X_train, y_train, validation_split=0.2, epochs=200, batch_size=50)

Epoch 1/200
10/10 [==============================] - 1s 54ms/step - loss: 0.6544 - accuracy: 0.6107 - val_loss: 0.6141 - val_accuracy: 0.6379
Epoch 2/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6274 - accuracy: 0.6698 - val_loss: 0.5967 - val_accuracy: 0.6466
Epoch 3/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6065 - accuracy: 0.6923 - val_loss: 0.5823 - val_accuracy: 0.6552
Epoch 4/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5886 - accuracy: 0.7010 - val_loss: 0.5718 - val_accuracy: 0.6638
Epoch 5/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5858 - accuracy: 0.6975 - val_loss: 0.5635 - val_accuracy: 0.6466
Epoch 6/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5648 - accuracy: 0.7288 - val_loss: 0.5562 - val_accuracy: 0.6466
Epoch 7/200
10/10 [==============================] - 0s 6ms/step - loss: 0.5505 - accuracy: 0.7117 - val_loss: 0.5510 - val_accuracy: 0.6552
Epoch 8/200


In [ ]:
# 모델 평가
acc = model.evaluate(X_test, y_test)
print(f'Accuracy: {acc[1]:.4f}')

6/6 [==============================] - 0s 2ms/step - loss: 0.4788 - accuracy: 0.8073
Accuracy: 0.8073


## 테스트

In [ ]:
index = 10
test_data = X_test[index, :].reshape(1, -1)
test_data

array([[-0.54791859,  2.38188392,  0.04624525,  4.92186584, -0.69289057,
         0.34362394,  0.31144581,  2.44704844]])

In [ ]:
label = y_test[index]
int(label)

1

In [ ]:
pred = model.predict(test_data)
pred

array([[0.7238406]], dtype=float32)

In [ ]:
int(pred[0][0] > 0.5)

1

## 은닉층 추가

In [ ]:
# 모델 정의
model = Sequential()
model.add(Dense(24, input_shape=(8,), activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 24)                216       
_________________________________________________________________
dense_4 (Dense)              (None, 12)                300       
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 9         
Total params: 629
Trainable params: 629
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 모델 설정
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [ ]:
# 모델 실행
history = model.fit(X_train, y_train, validation_split=0.2, epochs=200, batch_size=50)

Epoch 1/200
10/10 [==============================] - 1s 22ms/step - loss: 0.6395 - accuracy: 0.7005 - val_loss: 0.6443 - val_accuracy: 0.6034
Epoch 2/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6100 - accuracy: 0.7309 - val_loss: 0.6337 - val_accuracy: 0.6379
Epoch 3/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6024 - accuracy: 0.7237 - val_loss: 0.6249 - val_accuracy: 0.6207
Epoch 4/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5794 - accuracy: 0.7334 - val_loss: 0.6182 - val_accuracy: 0.6121
Epoch 5/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5723 - accuracy: 0.7279 - val_loss: 0.6117 - val_accuracy: 0.6207
Epoch 6/200
10/10 [==============================] - 0s 6ms/step - loss: 0.5631 - accuracy: 0.7492 - val_loss: 0.6039 - val_accuracy: 0.6207
Epoch 7/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5353 - accuracy: 0.7437 - val_loss: 0.5962 - val_accuracy: 0.6293
Epoch 8/200


In [ ]:
# 모델 평가
acc = model.evaluate(X_test, y_test)
print(f'Accuracy: {acc[1]:.4f}')

6/6 [==============================] - 0s 2ms/step - loss: 0.8238 - accuracy: 0.7500
Accuracy: 0.7500
